set schema 'APP';

create table constructo_user
(
    id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
    firstName varchar(100),
    lastName varchar(100),
    username varchar(100),
    email varchar(200),
    password varchar(200),
    role varchar(50) not null
)

